apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pg-pvc
  namespace: {{ .Release.Namespace | default "litellm" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # 5 Gigabytes is plenty for LiteLLM metadata logs