apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-litellm
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: litellm-port
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-litellm-stack