apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-qdrant
spec:
  serviceName: {{ .Release.Name }}-qdrant
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.18.0
          env:
            - name: QDRANT__SERVICE__API_KEY
              value: {{ .Values.qdrant.apiKey | quote }}
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: qdrantdata
              mountPath: /qdrant/storage
  volumeClaimTemplates:
    - metadata:
        name: qdrantdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
        volumeName: {{ .Release.Name }}-qdrant-pv
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
spec:
  ports:
    - port: 6333
  selector:
    app: qdrant
    