# Shared Data PVC (Used by API and Worker)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "{{ .Values.global.hostMountPath }}/shared-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: {{ .Release.Name }}-data-pv
---
# Postgres Local Host Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pg-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.hostMountPath }}/postgres"
---
# Qdrant Local Host Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-qdrant-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.global.hostMountPath }}/qdrant"