apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      initContainers:
        - name: wait-for-api
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -w 2 api 8000; do echo "waiting for api..."; sleep 2; done;']
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "/app/scripts/run-worker.sh"]
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-crawler-env
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-pvc