{{- if .Values.gitea.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gitea.persistence.size }}
  {{- if .Values.gitea.persistence.storageClass }}
  storageClassName: {{ .Values.gitea.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
