apiVersion: v1
kind: Service
metadata:
  name: gitea-svc
spec:
  selector:
    app: gitea
  ports:
    - port: {{ .Values.gitea.service.port }}
      targetPort: {{ .Values.gitea.service.targetPort }}
