apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: {{ .Values.gitea.replicaCount }}
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: "{{ .Values.gitea.image.repository }}:{{ .Values.gitea.image.tag }}"
          imagePullPolicy: {{ .Values.gitea.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.gitea.service.targetPort }}
          env:
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea-secret
                  key: GITEA__database__PASSWD
          envFrom:
            - configMapRef:
                name: gitea-config
          volumeMounts:
            {{- if .Values.gitea.persistence.enabled }}
            - name: gitea-data
              mountPath: /data
            {{- end }}
      volumes:
        {{- if .Values.gitea.persistence.enabled }}
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-pvc
        {{- end }}
