apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
type: Opaque
data:
  # base64 encoded by Helm
  GITEA__database__PASSWD: {{ .Values.gitea.env.dbPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # base64 encoded by Helm
  POSTGRES_PASSWORD: {{ .Values.postgres.env.password | b64enc | quote }}
