apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "custom-jenkins.fullname" . }}
  labels:
    {{- include "custom-jenkins.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "custom-jenkins.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "custom-jenkins.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: jenkins
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetHttpPort }}
              protocol: TCP
            - name: agent
              containerPort: {{ .Values.service.agentPort }}
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: {{ .Values.jenkins.javaOpts | quote }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: jenkins-home
              mountPath: /var/jenkins_home
            {{- end }}
            {{- if .Values.dockerSocket.enabled }}
            - name: docker-sock
              mountPath: /var/run/docker.sock
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
        {{- end }}
        {{- if .Values.dockerSocket.enabled }}
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        {{- end }}
