apiVersion: v1
kind: Service
metadata:
  name: {{ include "custom-jenkins.fullname" . }}
  labels:
    {{- include "custom-jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "custom-jenkins.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
    - name: agent
      port: {{ .Values.service.agentPort }}
      protocol: TCP
      targetPort: agent
