apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  OLLAMA_API_BASE: "http://host.docker.internal:11434"
  NVIDIA_API_BASE: "https://integrate.api.nvidia.com/v1"
  REDIS_HOST: ""
  REDIS_PORT: "6379"
